### ISSUE TITLE
最新代码报下面的问题

### ISSUE THREAD

**Issue by HailiangQin** [iiwen/dingdong-pro#13]
![捕获](https://user-images.githubusercontent.com/75285547/167893129-06429122-ddf9-4fb5-8b13-1769f8cd6371.JPG)

**Comment by iiwen** [comment]
您好，请按照提示检查一下配置是否有问题。如果无问题，说明您的账号被风控了

**Comment by good1357** [comment]
<img width="490" alt="微信截图_20220515110839" src="https://user-images.githubusercontent.com/103917536/168455447-f2564833-396c-4486-a9df-5aae3e205cca.png">
报错
cn.hutool.core.io.IORuntimeException: File not exist: sign.js
	at cn.hutool.core.io.file.FileReader.checkFile(FileReader.java:300)
	at cn.hutool.core.io.file.FileReader.<init>(FileReader.java:57)
	at cn.hutool.core.io.file.FileReader.create(FileReader.java:37)
	at cn.hutool.core.io.FileUtil.readString(FileUtil.java:1872)
	at cn.hutool.core.io.FileUtil.readString(FileUtil.java:1860)
